# Generated by Django 3.2.13 on 2022-05-05 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_client_operator_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='operator_code',
            field=models.CharField(max_length=3, verbose_name='Код оператора'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='date_end',
            field=models.DateField(verbose_name='Дата окончание рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='date_start',
            field=models.DateField(verbose_name='Дата начала рассылки'),
        ),
    ]
