# Generated by Django 3.2.13 on 2022-05-06 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220506_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='time_start',
        ),
        migrations.AlterField(
            model_name='mailing',
            name='date_end',
            field=models.DateTimeField(verbose_name='Дата окончание рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='date_start',
            field=models.DateTimeField(verbose_name='Дата начала рассылки'),
        ),
    ]
